name: 'transformations'
version: '1.0'
config-version: 2

profile: 'sqlite'
source-paths: ['models']
target-path: 'target'
clean-targets:
  - target
  - dbt_modules

models:
  transformations:
    +materialized: view  # Can be 'view', 'table', or 'incremental'
