name: 'transformations'
version: '1.0'
config-version: 2

profile: 'sqlite'
model-paths: ['models']
target-path: 'target'
clean-targets:
  - target
  - dbt_modules

models:
  transformations:
    +materialized: view  # Default materialization for all models
    stock_data_transformed:
      +materialized: view
    exclude_weekend_data:
      +materialized: view
